package peak.can.PCAN_WINDOWS.jna.structures;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class tagTPCANMsgFD extends Structure {
	/** 11/29-bit message identifier */
	public int ID;
	/** Type of the message */
	public byte MSGTYPE;
	/** Data Length Code of the message (0..15) */
	public byte DLC;
	/**
	 * Data of the message (DATA[0]..DATA[63])<br>
	 * C type : BYTE[64]
	 */
	public byte[] DATA = new byte[64];
	public tagTPCANMsgFD() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("ID", "MSGTYPE", "DLC", "DATA");
	}
	/**
	 * @param ID 11/29-bit message identifier<br>
	 * @param MSGTYPE Type of the message<br>
	 * @param DLC Data Length Code of the message (0..15)<br>
	 * @param DATA Data of the message (DATA[0]..DATA[63])<br>
	 * C type : BYTE[64]
	 */
	public tagTPCANMsgFD(int ID, byte MSGTYPE, byte DLC, byte DATA[]) {
		super();
		this.ID = ID;
		this.MSGTYPE = MSGTYPE;
		this.DLC = DLC;
		if ((DATA.length != this.DATA.length))
			throw new IllegalArgumentException("Wrong array size !");
		this.DATA = DATA;
	}
	public tagTPCANMsgFD(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends tagTPCANMsgFD implements Structure.ByReference {

	};
	public static class ByValue extends tagTPCANMsgFD implements Structure.ByValue {

	};
}
