#!/bin/bash

exclude=""

#echo "\nReading filesystem structure..."
files=$( find -name "Release" )
nfiles=$( find -name "Release" | wc -l )
tmp=$(echo "$files" | sed -n "1"p | cut -c 3-)
exclude="${tmp}"

for i in 'CMakeFiles' 'Makefile' 'CMakeCache.txt' 'CMakeLists.txt' 'cmake_install.cmake'
do
  files=$( find -name "$i" )
  nfiles=$( find -name "$i" | wc -l )
  for j in $(seq 1 $nfiles)
  do
    tmp=$(echo "$files" | sed -n "$j"p | cut -c 3-)
    exclude="${exclude}|${tmp}"
  done
done

#echo "\nReading .cproject..."
first=1
while IFS= read -r line
do
  search=$(echo "$line" | grep "excluding")
  if [ "$first" == 1 ] && [ -n "$search" ]
  then
    first=0
    top=$(echo "$search" | cut -d'"' -f 1)
    tmp=$(echo "$search" | cut -d'"' -f 2)
    bottom=$(echo "$search" | cut -d'"' -f 3-)
    IFS='|'
    read -ra ADDR <<< "$tmp"
    for path in "${ADDR[@]}"
    do
      add=1
      for i in 'Release' 'CMakeFiles' 'Makefile' 'CMakeCache.txt' 'CMakeLists.txt' 'cmake_install.cmake'
      do
        if [[ "$path" == *$i* ]]
        then
          add=0
        fi
      done
      if [ "$add" == 1 ]
      then
        exclude="${exclude}|${path}"
      fi
    done
    IFS=' '
    #echo "\nExcluding files generated by CMake..."
    exclude="${top}\"${exclude}\"${bottom}"
    echo "$exclude" >> "${1}_new"
  else
    echo "$line" >> "${1}_new"
  fi
done < "$1"

mv "${1}_new" "$1"
#echo "Done"
